spring.data.mongodb.uri=mongodb+srv://aymanesenhaji9_db_user:Aymane1234@cluster0.tseckvg.mongodb.net/sampledb?retryWrites=true&w=majority
spring.data.mongodb.database=sampledb
spring.output.ansi.enabled=ALWAYS
